dist: trusty
sudo: required
services:
- docker
language: node_js
node_js:
- 9.5.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - ATOMIST_TEAM=T29E48P34
  - secure: Dsp+D8rN+Br09dW3CpPChLkwvAWgMBqk4h+1Q6J508h6cL5UGZRqXIYRbmrOTNQR126URrYU8YMfR/9M66AolEUVaFhvJrktK/1RsGp1KYS7NAphvl7SlbDYr6AHYHCwM8Z62sU2Ni/YNcsrSlQeRTK1+mWYV93w+VQMdoWLoKoRT+bf8soWZIWEP8pXp/ex+ZMNGvS7elnX2CQITkSMCo876T60siGRPd7TSgadfwL7zuY5bxyFGBiG4vYBHyR4hmkr6pSMOmuWF0edxqjjg/NrMKdP+SC2uppCkftV+I9EByd7Mx9cPa0HRRogmjvhgJEZ4VLxIIzCLehmNRAlctFFPrY+RTEuOWoRhESvNT+IYjaadI1nD8/JG/12zLbJTryFW9f6JjAi/AZXN4gwqCO9MK7gMzL01+Id+j2gEIL59ThmcMPfndDdOyQvC7h4q3DH7xtsXGLmz6UzwrG6d9tOUiQ8cDGRniBMTSALtvPze8PjuJ+2BRHDMfl18Yc2QaRywpVY58KzSLKLNmAM54PiHn+PY9nL8U4uHFWRPPG3/Lq8vjlsOKsZORdJkCisH3SZNOzAWUbWBdtTEI5nQgDe0K2tgEAqTFyq8S1+Hy9WbY3Ljvx29Q+spgQn1Mqtb/PKsUZSKjcrmrwzl7fTyBVM/Ny7BewMLS/OV8LNw5o=
  - DOCKER_REGISTRY=atomist
  - DOCKER_USER=atomist
  - secure: Ol1rz7ZpmvW1w4RWyRdPJ8VViwSzgg8E97zrMF5GXwKYig1j5AgbxCOXi04cq3O326qWrR0NrOLe+RD/Omg1H24pCb6WJuiiwpSudZVueSEwuPy8GzZSaP0wwLz72Sc1KTxCLuccWms2gwMQtpAtWUFOEkztWSKwnymjGcKheG/SWT+Gk3f0e0osimxscpvdRusseUOGiGHiw624Ppiuyv+auCoqEqQhOr4p6XWo8ztsyyhex/HyY4ytM6sKe5e0/QrrdrKq83YkIGkR/9o3xitK/oCbTCsq7Sii7e/l2D6qwmqfjs6xDTuh/ldL75q7HxILZUJrRmBeRdqRf4/hza4NjEjiKxjrOX5MKa2q/abN8BXGlnQ66D5DKR6A9B5l1+GWANbGJ0MUqJSn4mOGMpyx5fRpqC98WJX+CxcR44IaetuA0KrCsX/pyB5aDp+2hErQT1Tix/i0UiM7wzemE+fY0NdjlQ3FUAJ0elmmENu4brLHB6XJUT/WiTQNO2ADIknO4tE0ej8pWv8ncAhvcfAk5wkSaquVa6fi0BpUyzmYPEab1h+VmskS6vQAsyY8opJtBLmO3bJRel0slQNuO74GXxiJubOxE4ITxKcVoBsHqpxwclo1oaJhbyFp5Y6HjR8rjdkR7zxEejLQqLqCn3tPSsx2M1bEr4Z7RrQxZ/8=
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
before_deploy:
- touch build/typedoc/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
