dist: trusty
sudo: required
services:
- docker
language: node_js
node_js:
- 9.5.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - ATOMIST_TEAM=T29E48P34
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: Dsp+D8rN+Br09dW3CpPChLkwvAWgMBqk4h+1Q6J508h6cL5UGZRqXIYRbmrOTNQR126URrYU8YMfR/9M66AolEUVaFhvJrktK/1RsGp1KYS7NAphvl7SlbDYr6AHYHCwM8Z62sU2Ni/YNcsrSlQeRTK1+mWYV93w+VQMdoWLoKoRT+bf8soWZIWEP8pXp/ex+ZMNGvS7elnX2CQITkSMCo876T60siGRPd7TSgadfwL7zuY5bxyFGBiG4vYBHyR4hmkr6pSMOmuWF0edxqjjg/NrMKdP+SC2uppCkftV+I9EByd7Mx9cPa0HRRogmjvhgJEZ4VLxIIzCLehmNRAlctFFPrY+RTEuOWoRhESvNT+IYjaadI1nD8/JG/12zLbJTryFW9f6JjAi/AZXN4gwqCO9MK7gMzL01+Id+j2gEIL59ThmcMPfndDdOyQvC7h4q3DH7xtsXGLmz6UzwrG6d9tOUiQ8cDGRniBMTSALtvPze8PjuJ+2BRHDMfl18Yc2QaRywpVY58KzSLKLNmAM54PiHn+PY9nL8U4uHFWRPPG3/Lq8vjlsOKsZORdJkCisH3SZNOzAWUbWBdtTEI5nQgDe0K2tgEAqTFyq8S1+Hy9WbY3Ljvx29Q+spgQn1Mqtb/PKsUZSKjcrmrwzl7fTyBVM/Ny7BewMLS/OV8LNw5o=
  - DOCKER_REGISTRY=atomist
  - DOCKER_USER=atomist
  - secure: E/xxg/APOCZDT1aT2DmsGmyywqwWPv5XOhl6t//cHxpxl74zejSPKMbnYuDaxnE9MV/qaX0kTSsm2uVOU+jiw5V6Jvz6o3qvgK6F7KlRYS9beQADH7DHCvCpZt4i4GkF4nWrFFyowUBNKrISg4E0UwzIW7S0y7LmRTjPebEBwA8uQjbScDE9XDCvfapmMjUWz2dPJQSKPqlEsucmvv9LZBK2vEHTfDFrzby/Sddbm/q7eh/bITTA5lKDqF0pmKaGJfKq5H916Pf5Oy0SC7LttpfNeShhTO/ozswTDrGuLldaVVMZvlqAUEiknfFHoPlQEAoazEVKJZ6FGa+5YBAW6Mbuq+mwGlit+SohyoopJ7fvHMveib4SoG5Adx+EBCq1HzVevID6aQOgtZd0OKWsfty75Iu05k0QwKpDoa2wyNlfpe5KVXQMWlbxJV2PhTSZbPVzigvyM61w+ykj24gvZdqVDCmOksxj6sJa8begDoOSUfBTAPcLhpeYUzFzXhtaNAOij4BCypJxDntMn4NA4BwokTWiCB/iXAUZBTj3XetCss769H9AwBdVsqew4RL0AMjRDHj8i2ER5cUstkbjaXzgA4QqCbtJ0BQcRAjAg9GjEIZ5FILUlz/FGc88TJZr7UK9umyFq9nZ+KGMK8tL3aRds9unn7ewHj4VZdiPfDA=
before_install:
- openssl aes-256-cbc -K $encrypted_1ec4abc792fb_key -iv $encrypted_1ec4abc792fb_iv
  -in .npmrc.enc -out .npmrc -d
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
before_deploy:
- touch build/typedoc/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
